name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Extrair projeto
        run: |
          mkdir project
          unzip BacBoMonitor_Android_CORRIGIDO.zip -d project

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android
        uses: android-actions/setup-android@v3

      - name: Instalar SDK
        run: sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10'

      - name: Compilar APK
        working-directory: project
        run: gradle assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: BacBoMonitor-APK
          path: project/app/build/outputs/apk/debug/app-debug.apk
